#!/usr/bin/with-contenv bash

run_jpanel () {
    echo -e "\n======================== 启动控制面板 ========================\n"
    cd ${JD_DIR}/jpanel
    pm2 start ecosystem.config.js
    if [[ $? -eq 0 ]]; then
        echo -e "控制面板启动成功...\n"
        echo -e "如未修改用户名密码，则初始用户名为：admin，初始密码为：123456\n"
        echo -e "请访问 http://<ip>:5678 登陆并修改配置...\n"
    else
        echo -e "控制面板启动失败，但容器将继续启动...\n"
    fi
}

run_jpanel 2>&1 | perl -pe "s|^(.+)|[cont-init.d] $(basename $0): \1|g"
